Bring main Up to Date with test Branch
Dbartra1/unraid_scripts pull request #11
Opened 2024-12-22 02:40 UTC by Dbartra1

## 📋 **Summary**  

This PR updates the `main` branch with the latest changes from the `test` branch. These updates include improvements to file transfer scripts, code cleanup, UI adjustments, and new synchronization methods.  

---

## 🛠️ **Changes Made**  

### 📂 **File Transfers**  
- ✅ **Renamed Scripts:** Improved script naming to better reflect their purpose.  
- 🧹 **Cleanup:** Removed extra test files, unnecessary directories, and redundant container files.  
- ⚡ **Added Rsync Script:**  
   - Syncs **only deltas** between two directories.  
   - **Pros:** Much faster.  
   - **Cons:** Theoretically less accurate, as it only compares **dates** and **file sizes**.  
- 🐢 **Added Hash-Based Sync Script:**  
   - Compares **all files** in directories using **hash values**.  
   - **Pros:** Extremely accurate.  
   - **Cons:** Very slow.  

### 🖥️ **UI Updates**  
- 📴 **Removed On/Off Button:**  
   - UI no longer includes the on/off button.  
   - This functionality will now be managed via **cron jobs** and **server-side database tracking**.  
- 🎨 **Reformatted UI:**  
   - Updated layout to better align with project requirements.  

---

## ✅ **Testing & Verification**  
- All file transfer scripts have been **confirmed to work in a local environment**.  

---

## **How to Test**  
1. Run the updated transfer scripts locally.  
2. Verify delta and hash-based sync methods work as expected.  
3. Check the restructured UI for usability and functionality.  

---

## **Related Issues / Notes**  
- No known issues at this time.

2025-01-02 23:27 UTC, visherj requested changes
I've got some small change suggestions and some questions to help me understand certain things better. Impressive work dude!

2025-01-02 23:27 UTC, visherj commented on app/Dir_cleanup.py
> +
I feel like it would be useful to include a comment somewhere up here with a small description of the purpose of this script.

2025-01-02 23:27 UTC, visherj commented on app/Dir_cleanup.py
> +    level=logging.DEBUG,
Could be helpful to make this configurable.

2025-01-02 23:27 UTC, visherj commented on app/Dir_cleanup.py
> +    for entry in os.scandir(directory):
Is it possibly valuable to refactor the order of operations of this script so this call to `os.scandir(directory)` isn't repeated twice (here and in `remove_empty_dirs` below) in each iteration of the first `for` in `check_and_clean_directories`?

2025-01-02 23:27 UTC, visherj commented on app/Docker_config_backup.py
> +        required_keys = ["backup_location", "retention_days", "containers"]
I think for something like this [you could follow conventions](https://stackoverflow.com/questions/7078731/conventions-on-creating-constants-in-python) for "declaring a constant" in Python (quotes because Python doesn't really do constants).

2025-01-02 23:27 UTC, visherj commented on app/Docker_config_backup.py
> +        if PAUSE_CONTAINERS:
Could probably be an `elif` and looks like you have the wrong check.

2025-01-02 23:27 UTC, visherj commented on app/Docker_config_backup.py
> +        subprocess.run(["docker", action, container_name], check=True)
What exactly is happening here?

2025-01-02 23:27 UTC, visherj commented on app/File_transfer_IDRAC.py
>  logging.basicConfig(
Another script which would benefit from a purpose comment. Also has this been tested in any way? (same question for all scripts in this dir)

2025-01-02 23:27 UTC, visherj commented on config/backup_config.json
> +    "backup_location": "//192.168.0.55/appdata/backup",
What address is this?

2025-01-02 23:27 UTC, visherj commented on app/File_transfer_detailed.py
> +load_dotenv()
Is it necessary to have this script in addition to `File_transfer_IDRAC.py`, or would it be possible to combine the 2 to reduce duplicate code? (I skimmed here and just saw some dupe names so if I'm totally wrong feel free to shame me)

2025-01-06 00:01 UTC, Dbartra1 commented on app/Dir_cleanup.py
> +
I added a docstring with a brief description of what the script does. Let me know if you need more detail.

2025-01-06 02:55 UTC, Dbartra1 commented on app/Dir_cleanup.py
> +    level=logging.DEBUG,
Here is my proposed method of making the log level configurable. This requires a environmental variable and a dict with preestablished log levels mapped to strings as shown in lines 27-35. I am not against doing this, but this is about as far as I am willing to go to implement it. This will also require changes to all scripts in the container, which I can do on the next PR.

2025-01-06 03:00 UTC, Dbartra1 commented on app/Docker_config_backup.py
> +        required_keys = ["backup_location", "retention_days", "containers"]
This has been fixed.

2025-01-06 03:40 UTC, Dbartra1 commented on app/Dir_cleanup.py
> +    for entry in os.scandir(directory):
This is my attempt to simplify the logic into one function. This function only calls to os.scandir once per directory, providing some additional performance and readability.

2025-01-06 04:09 UTC, Dbartra1 commented on app/File_transfer_detailed.py
> +load_dotenv()
SOOO you are right, it did not need to be two scripts, so here is what I did.
- I pulled all of the logic for interacting with IDRAC via the api over to the File_transfer_detailed.py script, as the file sync logic is the same in both. 
- I implemented a env variable to "turn on" the IDRAC function via a bool. 
- In moving the logic over for IDRAC, I found a potential infinite execution of the IDRAC power on logic, so I added a max retries. 
- I removed the other script as it is not needed.

2025-01-06 05:17 UTC, Dbartra1 commented on app/File_transfer_detailed.py
> +load_dotenv()
I also implemented the new log structure that allows configuration via the env variable LOG_LEVEL.

2025-01-06 05:22 UTC, Dbartra1 commented on config/backup_config.json
> +    "backup_location": "//192.168.0.55/appdata/backup",
That was a dummy address used for testing. It has been removed.

2025-01-06 06:13 UTC, Dbartra1 commented on app/Docker_config_backup.py
> +        subprocess.run(["docker", action, container_name], check=True)
This function is a lightweight way of pausing or starting docker containers. If you look in the main logic, you will see when the container_name and action variables are passed to it (lines 120-126). The reasoning behind this is that when a docker container is active, you can't copy files that are locked by active processes. Pausing the container allows you to copy the entire appdata directory. There are a few files that you still can't copy, like keys, but those are not needed. I hope that makes sense.

2025-01-06 06:19 UTC, Dbartra1 commented on app/Docker_config_backup.py
> +        if PAUSE_CONTAINERS:
You are correct, and I went ahead and corrected it. The "start" and "stop" checks needed to be mutually exclusive.

2025-01-08 01:00 UTC, visherj approved these changes

2025-01-08 03:38 UTC, merged